import type { Memory, Policy, BudgetInput } from './types';
export const DEFAULT_POLICY: Policy = { reserveDays: 14, maxMonthlyUsdfc: 0.5, minUtility: 32, allowCompaction: true };
export const DEMO_BUDGET: BudgetInput = { availableUsdfc: 0.38, existingMonthlyUsdfc: 0.24, storagePerTibMonth: 2.5, datasetFeeMonth: 0.12, addBaseFee: 0.008, addPieceFee: 0.003, copies: 2, newDataset: false };
const trace = Array.from({length: 120}, (_,i) => `Step ${i + 1}: fetched the same provider status. Response 200. Provider available. Latency ${80 + i % 30}ms. No new information. Repeated diagnostic context.`).join('\n');
export const SEED_MEMORIES: Memory[] = [
 {id:'mission',title:'Mission & safety boundaries',kind:'core',importance:100,accesses:86,ageDays:2,pinned:true,content:'Mission: preserve useful research while respecting a finite storage budget. Never discard a pinned memory. Never claim a receipt proves semantic correctness. Use Calibration only. Stop new uploads if financial telemetry is unavailable. Mission owner: the researcher. Recoverable source documents stay local until the user removes them.'},
 {id:'discovery',title:'The result that changed the experiment',kind:'research',importance:94,accesses:32,ageDays:1,pinned:false,content:'Finding: batching related observations into one archive avoids repeated per-piece fees. Evidence: the Filecoin Warm Storage price list distinguishes base fees and per-piece fees. Keep source hashes in a manifest. Critical: compression reduces bytes, but a dataset proving fee remains until the dataset is empty. Conclusion: optimize the decision unit, not just payload bytes.'},
 {id:'experiment',title:'Experiment 024 · working notes',kind:'research',importance:71,accesses:12,ageDays:3,pinned:false,content:'Result: the retrieval check matched the uploaded SHA-256. We tested a memory bundle, downloaded it, and compared every byte. Important: this checks retrieval integrity, not an independently verified PDP challenge. The archive contains an extractive summary and the source digest. '+trace.slice(0,4200)},
 {id:'tool-trace',title:'Repeated tool-call traces',kind:'trace',importance:18,accesses:1,ageDays:8,pinned:false,content:trace},
 {id:'drafts',title:'Superseded answer drafts',kind:'artifact',importance:27,accesses:2,ageDays:6,pinned:false,content:'Draft status: superseded by the final research finding. No unique facts remain in this version. '+trace.slice(0,6800)},
 {id:'recovery',title:'Recovery & provenance manifest',kind:'core',importance:97,accesses:28,ageDays:1,pinned:true,content:'Recovery procedure: locate the receipt by content hash. Download the bundle from a successful provider. Verify SHA-256 before reading memories. Each compacted memory names its original SHA-256 digest. Source excerpts are verbatim and ordered. If a provider fails, try another copy. Retention decisions are policy outputs, not guarantees of factual correctness.'},
 {id:'provider-notes',title:'Provider comparison notes',kind:'research',importance:62,accesses:7,ageDays:4,pinned:false,content:'Observation: provider redundancy requires separate datasets, with separate proving fees. Result: two copies protect against a single unavailable provider. Important: keep the receipt with provider ID, dataset ID, piece ID, and retrieval URL. '+trace.slice(0,1600)},
 {id:'scratch',title:'Expired scratchpad',kind:'trace',importance:9,accesses:0,ageDays:14,pinned:false,content:'Temporary scratchpad, expired. These repeated checks were resolved. '+trace.slice(0,9000)},
];
